# Arrays en Numpy

In [3]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [5]:
vector = np.array([30,29,35,31,33,36,42])
print(vector)

[30 29 35 31 33 36 42]


In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
tensor = np.array([[1,2],[3,4],[5,6],[7,8]])
print(tensor)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [15]:
diag = np.diag([1,2,3,4,5,6,7])
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [16]:
random = np.random.random((2,3))
print(random)

[[0.99292438 0.84327964 0.69476081]
 [0.79272935 0.26099878 0.42153179]]


# manipulacion de arrays numpy

In [20]:
array = np.array([[1,2,3],[4,5,6]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


In [22]:
z = np.array(3,dtype = np.uint8)
print(z)

3


In [23]:
double_array = np.array([1,2,3], dtype = 'd')
print(double_array)

[1. 2. 3.]


In [24]:
z = z.astype(np.float64)
print(z)

3.0


In [25]:
array = np.array([[1,2,3],[4,5,6]])
add = np.sum(array)
print(add)

21


In [26]:
array = np.array([[1,2,3],[4,5,6]])
mean = np.mean(array)
print(mean)


3.5


In [27]:
std = np.std(array)
print(std)

1.707825127659933


# Indexacion y Slicing

In [41]:
import numpy

array = (np.array([10,20,30,40,50]))
print(array[1])
print(array[-1])

20
50


In [ ]:
#sacamos una porcion del vector en este caso desde el elemento en la posicion 1 hasta la 4
print(array[1:4])

[20 30 40]


In [ ]:
#como estamos intentando ejecutar una posicion que no existe simplemente nos da hasta el ultimo elemento posible
print(array[1:7])

[20 30 40 50]


In [ ]:
#en este caso el vector se da en orden desde la posicion 1 hasta -7 posiciones como no tenemos nos muestra un []
print(array[1:-7])

[]


In [ ]:
# Realizamos indexacion booleana donde nos identifica bajo una condicion dada
array = (np.array([10,20,30,40,50]))
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [ ]:
# a los indices podemos guardarllos bajo una variable para que nos traiga solo un parte del vector, es igual que el ejercicio de arriba 
#sin embargo aqui definimos en variables especificamente la porcion que queremos sacar del vector
index = [2,0,4]
print(array[index])

[30 10 50]


In [ ]:
#indexacion con multiples indices
array = np.random.randint(1,10,size = (3,3))
print(array)
print(array[0,1])

[[2 2 2]
 [2 5 5]
 [2 6 9]]
2


In [ ]:
#matrices bidimensionales basado en una porcion de una matriz de mas dimensiones, util al trabajar con grandes volumenes de datos
print(array[:2,:2])

[[2 2]
 [2 5]]


# Boradcasting

In [44]:
prices = np.array([100,200,300])
discount= np.array([0.9])
discount_prices = prices * discount
print(discount_prices)


[ 90. 180. 270.]


In [48]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([1,2,3])
discount_prices = prices + discount
print(prices)
print(discount_prices)

[[106 257 220]
 [401 261 343]
 [179 369 364]]
[[107 259 223]
 [402 263 346]
 [180 371 367]]


In [ ]:
array = np.array([1,2,3,4,5])
print(np.all(array>0)) #todos los slementos deben cumplir la condicion para que el retorno sea true.

True


In [ ]:
print(np.all(array>0)) #cualquier elemento puede cumplir la condicion para retornar true

# concatenated

In [57]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated = np.concatenate((array_a, array_b))
print(concatenated)
# teniendo dos arrays usamos la funcion de numpy concatenate o concat para concatenar dos vectores.
concatenated_a = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_a)
print(concatenated_ab)

[1 2 3 4 5 6]
[1 2 3 1 2 3]
[1 2 3 4 5 6]


# Stacking

In [ ]:
#El stacking nos permite concatenar ya sea de manera vertical u horizontal con la funcion np.vstack o np.hstack
stacked_v = np.vstack((array_a,array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [60]:
stacked_h = np.hstack((array_a,array_b))
print(stacked_h)

[1 2 3 4 5 6]


# Split

In [ ]:
array_c = np.arange(1,10) #creamos un array entre un rango entre el 1 al 10
split_array = np.split(array_c,3) #usamos la funcion split que nos permite separar en arrays mas pequeños, en este caso en 3
print(array_c) #imprimimos el array completo
print(split_array) #imprimimos el array en 3 arrays mas pequeños respectivamente sus valores.

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
