# Arrays en Numpy

In [3]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [5]:
vector = np.array([30,29,35,31,33,36,42])
print(vector)

[30 29 35 31 33 36 42]


In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
tensor = np.array([[1,2],[3,4],[5,6],[7,8]])
print(tensor)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [15]:
diag = np.diag([1,2,3,4,5,6,7])
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [16]:
random = np.random.random((2,3))
print(random)

[[0.99292438 0.84327964 0.69476081]
 [0.79272935 0.26099878 0.42153179]]


# manipulacion de arrays numpy

In [20]:
array = np.array([[1,2,3],[4,5,6]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


In [22]:
z = np.array(3,dtype = np.uint8)
print(z)

3


In [23]:
double_array = np.array([1,2,3], dtype = 'd')
print(double_array)

[1. 2. 3.]


In [24]:
z = z.astype(np.float64)
print(z)

3.0


In [25]:
array = np.array([[1,2,3],[4,5,6]])
add = np.sum(array)
print(add)

21


In [26]:
array = np.array([[1,2,3],[4,5,6]])
mean = np.mean(array)
print(mean)


3.5


In [27]:
std = np.std(array)
print(std)

1.707825127659933


# Indexacion y Slicing

In [41]:
import numpy

array = (np.array([10,20,30,40,50]))
print(array[1])
print(array[-1])

20
50


In [ ]:
#sacamos una porcion del vector en este caso desde el elemento en la posicion 1 hasta la 4
print(array[1:4])

[20 30 40]


In [ ]:
#como estamos intentando ejecutar una posicion que no existe simplemente nos da hasta el ultimo elemento posible
print(array[1:7])

[20 30 40 50]


In [ ]:
#en este caso el vector se da en orden desde la posicion 1 hasta -7 posiciones como no tenemos nos muestra un []
print(array[1:-7])

[]


In [ ]:
# Realizamos indexacion booleana donde nos identifica bajo una condicion dada
array = (np.array([10,20,30,40,50]))
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [ ]:
# a los indices podemos guardarllos bajo una variable para que nos traiga solo un parte del vector, es igual que el ejercicio de arriba 
#sin embargo aqui definimos en variables especificamente la porcion que queremos sacar del vector
index = [2,0,4]
print(array[index])

[30 10 50]


In [ ]:
#indexacion con multiples indices
array = np.random.randint(1,10,size = (3,3))
print(array)
print(array[0,1])

[[2 2 2]
 [2 5 5]
 [2 6 9]]
2


In [ ]:
#matrices bidimensionales basado en una porcion de una matriz de mas dimensiones, util al trabajar con grandes volumenes de datos
print(array[:2,:2])

[[2 2]
 [2 5]]


# Boradcasting

In [44]:
prices = np.array([100,200,300])
discount= np.array([0.9])
discount_prices = prices * discount
print(discount_prices)


[ 90. 180. 270.]


In [48]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([1,2,3])
discount_prices = prices + discount
print(prices)
print(discount_prices)

[[106 257 220]
 [401 261 343]
 [179 369 364]]
[[107 259 223]
 [402 263 346]
 [180 371 367]]


In [ ]:
array = np.array([1,2,3,4,5])
print(np.all(array>0)) #todos los slementos deben cumplir la condicion para que el retorno sea true.

True


In [ ]:
print(np.all(array>0)) #cualquier elemento puede cumplir la condicion para retornar true

# concatenated

In [57]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated = np.concatenate((array_a, array_b))
print(concatenated)
# teniendo dos arrays usamos la funcion de numpy concatenate o concat para concatenar dos vectores.
concatenated_a = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_a)
print(concatenated_ab)

[1 2 3 4 5 6]
[1 2 3 1 2 3]
[1 2 3 4 5 6]


# Stacking

In [ ]:
#El stacking nos permite concatenar ya sea de manera vertical u horizontal con la funcion np.vstack o np.hstack
stacked_v = np.vstack((array_a,array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [60]:
stacked_h = np.hstack((array_a,array_b))
print(stacked_h)

[1 2 3 4 5 6]


# Split

In [ ]:
array_c = np.arange(1,10) #creamos un array entre un rango entre el 1 al 10
split_array = np.split(array_c,3) #usamos la funcion split que nos permite separar en arrays mas pequeños, en este caso en 3
print(array_c) #imprimimos el array completo
print(split_array) #imprimimos el array en 3 arrays mas pequeños respectivamente sus valores.

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# identify and unique responses

In [ ]:
#vamos a identificar valores unicos
survey_responses = np.array(["good","excelent","bad",
                             "good","bad","excelent",
                             "good","good","bad",
                             "excelent"                             
                             ])
print(np.unique(survey_responses))

['bad' 'excelent' 'good']


In [ ]:
#Realizamos el conteo de cuantas veces se encuentra un valor en la lista
unique_elements, count = np.unique(survey_responses, return_counts = True)
print(unique_elements)
print(count)

['bad' 'excelent' 'good']
[3 3 4]


In [ ]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)
array_x[1:3] = [10,11]
print(array_x)
print(view_y)
#observamos que es posible modificar la información de origen por ello al realizar algun proceso de transformacion siempre se recomienda 
#realizar copias de la lista,tupla,conjunto, dataframe,etc


[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [ ]:
array_x = np.arange(10)
copy_x = array_x[[1,2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10,11]
print(array_x)
print(copy_x)
#obsrevamos que se mantienen los valores en la copia



[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


# Transformations with arrays
## Transposed

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed_matrix = matrix.T #la funcion T ns da la transpuesta de la matriz
print(matrix)
print(transposed_matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Shape

In [ ]:
array = np.arange(1,13)
reshaped_array = array.reshape(3,4) #la funcion reshape me cambia la dimensionalidad que del array que tenga conservando valores
print(array)
print(reshaped_array)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## reverse

In [ ]:
reversed_array = array[::-1] #cambiamos el orden de manera del ultimo elemento al primero respectivamente
print(array) #imprimimos el array sin modificaciones
print(reversed_array) #nos muestra el array modificado el orden


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


## flattening

In [ ]:
# transformamos la dimensionalidad de una matriz en un venctor, lo "aplanamos", esta transformacion es usada en deep learning
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened_array = matrix.flatten()
print(matrix)
print(flattened_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


# Ejercicio practico
Ejercicio: Análisis de Ventas Mensuales con NumPy
El objetivo de este ejercicio es trabajar con arrays de NumPy para analizar y manipular datos de ventas de tres productos a lo largo de un año. A través de diversas operaciones, explorarás cómo usar NumPy para obtener estadísticas, realizar manipulaciones avanzadas y aplicar técnicas de indexación para extraer información clave.

Instrucciones:

Paso 1: Crear Arrays con Datos de Ventas

Usa la librería numpy para crear los siguientes arrays:
meses: un array con los nombres de los meses del año.
ventas_A, ventas_B, ventas_C: arrays que representan las ventas mensuales de tres productos diferentes.
Paso 2: Estadísticas Básicas

Calcula la media y la suma de ventas para los productos A, B y C usando las funciones de NumPy.
Imprime estos valores en el formato siguiente:
Media de ventas Producto A: <valor>
Suma de ventas Producto A: <valor>
Repite para los productos B y C.
Paso 3: Manipulación y Análisis de Datos

Total de ventas por mes: Suma las ventas de los tres productos para cada mes.
Promedio de ventas por producto: Calcula el promedio de ventas por producto.
Mes con mayor y menor ventas: Identifica qué mes tuvo el total de ventas más alto y cuál el más bajo usando las funciones np.argmax y np.argmin.
Paso 4: Operaciones Avanzadas con NumPy

Reshape y Transposición:

Crea una matriz 2D con las ventas de los tres productos y transforma su forma (reshape) a un array tridimensional con dimensiones (3, 4, 3).
Transpone la matriz de ventas para que las filas se conviertan en columnas.
Invertir arrays: Invierte las ventas de cada producto en orden de meses.
Aplanar la matriz: Convierte la matriz de ventas a un array unidimensional.
Paso 5: Análisis de Elementos Únicos

Utiliza np.unique para encontrar los elementos únicos en los datos de ventas y cuenta cuántas veces aparece cada uno.
Paso 6: Indexación y Slicing

Ventas del primer trimestre: Extrae las ventas de los tres primeros meses del año.
Indexación booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
Selección avanzada: Usa una lista de índices para seleccionar las ventas de los meses pares (o selecciona los meses a tu elección) y muestra esas ventas en una nueva matriz.

In [109]:
# Paso 1
months = np.array([
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
])

product_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
product_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
product_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

In [120]:
# Paso 2
sum_sales_A = np.sum(product_A)
sum_sales_A = np.sum(product_B)
sum_sales_A = np.sum(product_C)
sum_sales_A = np.sum(product_A)
mean_sales_A = np.mean(product_A)
mean_sales_B = np.mean(product_B)
mean_sales_C = np.mean(product_C)
print("Media de ventas Producto A:"+"\n"
"Suma de ventas Producto A:"+"\n"
"Media de ventas Producto B:"+ "\n"
"Suma de ventas Producto B:"+ "\n"
"Media de ventas Producto C:"+ "\n"
"Suma de ventas Producto C:"+ "\n")
print(sum_sales_A)

Media de ventas Producto A:
Suma de ventas Producto A:
Media de ventas Producto B:
Suma de ventas Producto B:
Media de ventas Producto C:
Suma de ventas Producto C:

2750


In [141]:
#total de ventas por mes
total_sales_A = product_A+product_B+product_C
print(f"Para el mes de {months[0]} el total de ventas fue: {total_sales_A[0]}")
print(f"Para el mes de {months[1]} el total de ventas fue: {total_sales_A[1]}")
print(f"Para el mes de {months[2]} el total de ventas fue: {total_sales_A[2]}")
print(f"Para el mes de {months[3]} el total de ventas fue: {total_sales_A[3]}")
print(f"Para el mes de {months[4]} el total de ventas fue: {total_sales_A[4]}")
print(f"Para el mes de {months[5]} el total de ventas fue: {total_sales_A[5]}")
print(f"Para el mes de {months[6]} el total de ventas fue: {total_sales_A[6]}")
print(f"Para el mes de {months[7]} el total de ventas fue: {total_sales_A[7]}")
print(f"Para el mes de {months[8]} el total de ventas fue: {total_sales_A[8]}")
print(f"Para el mes de {months[9]} el total de ventas fue: {total_sales_A[9]}")
print(f"Para el mes de {months[10]} el total de ventas fue: {total_sales_A[10]}")
print(f"Para el mes de {months[11]} el total de ventas fue: {total_sales_A[11]}")


#promedio de ventas por producto
print(f"El promedio de ventas para el producto A fue de {mean_sales_A}")
print(f"El promedio de ventas para el producto A fue de {mean_sales_B}")
print(f"El promedio de ventas para el producto A fue de {mean_sales_C}")

#mes con mayor y menores ventas
Max_sales_month = np.argmax(product_A+product_B+product_C)
Min_sales_month_A = np.argmin(product_A)
Max_sales_month_B = np.argmax(product_B)
Min_sales_month_B = np.argmin(product_B)
Max_sales_month_C = np.argmax(product_C)
Min_sales_month_C = np.argmin(product_C)
print(f"El mes que mas tuvo ventas fue:{months[1]}\n"+
    f"con ventas por valor de:{Max_sales_month}")
print(Max_sales_month_A)
print(Min_sales_month_A)
print(Max_sales_month_B)
print(Min_sales_month_B)
print(Max_sales_month_C)
print(Min_sales_month_C)

productoA_B_C_2D= np.array([[150,200,250,300,220,210,180,190,230,240,280, 300],[180,210,230,250,270,260,240,250,270,290,310,330],[200,220,240,260,280,300,320,340,360,380,400,420]])
print(productoA_B_C_2D)

# Otra forma ventas_matrix = np.array([ventas_A, ventas_B, ventas_C])

print("Cambio de forma")
reshaped_array= productoA_B_C_2D.reshape(3, 4, 3)
print(reshaped_array)

print("Transupuesta")
transpuesta_producto= productoA_B_C_2D.T
print(transpuesta_producto)

print("Invierte Array")
meses_invertido= months[::-1].copy()

productoA_invertido = product_A[::-1].copy()
productoB_invertido = product_B[::-1].copy()
productoC_invertido = product_C[::-1].copy()
print(meses_invertido)
print(productoA_invertido)
print(productoB_invertido)
print(productoC_invertido)

print("Ventas_Aplanado")
Ventas_Aplanado= productoA_B_C_2D.flatten()
print(Ventas_Aplanado)

"""
Paso 5: Análisis de Elementos Únicos
Utiliza np.unique para encontrar los elementos únicos en los datos de ventas y cuenta cuántas veces aparece cada uno.
"""

print("Elementos y Conteo")
elementos_unico,conteo= np.unique(Ventas_Aplanado, return_counts=True )

print("Elementos unicos", elementos_unico)
print("Conteo", conteo)


"""
**Paso 6: Indexación y Slicing**

- Ventas del primer trimestre: Extrae las ventas de los tres primeros meses del año.
- Indexación booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
- Selección avanzada: Usa una lista de índices para seleccionar las ventas de los meses pares (o selecciona los meses a tu elección) y muestra esas ventas en una nueva matriz
"""

ventas_primer_Trimestre= np.array(total_sales_A[0:3])
print("Ventas totales primer trimestre ", ventas_primer_Trimestre)

ventas_mayor_cond= total_sales_A>800
print(months[ventas_mayor_cond])

print("Seleccion avanzada")
par = [0, 2, 4, 6, 8, 10]
ventas_par_seleccionados = productoA_B_C_2D[:, par]
print("Ventas en meses seleccionados:\n", ventas_par_seleccionados)


Para el mes de Enero el total de ventas fue: 530
Para el mes de Febrero el total de ventas fue: 630
Para el mes de Marzo el total de ventas fue: 720
Para el mes de Abril el total de ventas fue: 810
Para el mes de Mayo el total de ventas fue: 770
Para el mes de Junio el total de ventas fue: 770
Para el mes de Julio el total de ventas fue: 740
Para el mes de Agosto el total de ventas fue: 780
Para el mes de Septiembre el total de ventas fue: 860
Para el mes de Octubre el total de ventas fue: 910
Para el mes de Noviembre el total de ventas fue: 990
Para el mes de Diciembre el total de ventas fue: 1050
El promedio de ventas para el producto A fue de 229.16666666666666
El promedio de ventas para el producto A fue de 257.5
El promedio de ventas para el producto A fue de 310.0
El mes que mas tuvo ventas fue:Febrero
con ventas por valor de:11
11
0
11
0
11
0
[[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 36

# Operations withs lineal algebra

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#suma
sum = A+B
print(A)
print(B)
print(sum)



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [ ]:
#multiplicacion
product = np.dot(A,B)
print(product)


[[19 22]
 [43 50]]


In [146]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(A)
print(det_A)
print(inv_A)

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [147]:
#resolver Ax = b
b = np.array([9,11])
x = np.linalg.solve(A,b)
print(x)

[-7.  8.]


# Ejercicios Prácticos con NumPy
Vamos a consolidar lo que has aprendido con ejercicios exclusivos de NumPy, diseñados para reforzar tus habilidades y prepararte para las conexiones futuras con Pandas y Matplotlib.

Operaciones Básicas con Arrays
Instrucción: Crea dos arrays de 1D con valores enteros y realiza las operaciones de suma, resta, multiplicación, y división entre ellos.

In [148]:
import numpy as np

array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

suma = array1 + array2
resta = array1 - array2
multiplicacion = array1 * array2
division = array1 / array2

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

Suma: [11 22 33 44]
Resta: [ 9 18 27 36]
Multiplicación: [ 10  40  90 160]
División: [10. 10. 10. 10.]


## 2. Cálculos Estadísticos en Arrays
Instrucción: Dado un array de datos, calcula la media, mediana, varianza, y desviación estándar.

In [149]:

import numpy as np

datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviacion = np.std(datos)

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)
print("Desviación estándar:", desviacion)

Media: 57.44444444444444
Mediana: 67.0
Varianza: 484.02469135802465
Desviación estándar: 22.000561160071


## 3. Operaciones Matriciales
Instrucción: Crea dos matrices de 2x2 y realiza las operaciones de suma, resta, multiplicación (producto matricial) y cálculo de la inversa de una de ellas.

In [ ]:
import numpy as np

matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

suma_matrices = matriz1 + matriz2
resta_matrices = matriz1 - matriz2
producto_matrices = np.dot(matriz1, matriz2)
inversa_matriz1 = np.linalg.inv(matriz1)

print("Suma de matrices:\n", suma_matrices)
print("Resta de matrices:\n", resta_matrices)
print("Producto de matrices:\n", producto_matrices)
print("Inversa de la matriz 1:\n", inversa_matriz1)

## 4. Resolución de un Sistema de Ecuaciones Lineales
Instrucción: Resuelve el sistema de ecuaciones lineales dado por Ax=b, donde A es una matriz 2x2 y b es un vector de 2 elementos.

Ax=bAx = b

In [151]:
import numpy as np

A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

x = np.linalg.solve(A, b)
print("Solución del sistema de ecuaciones:", x)

Solución del sistema de ecuaciones: [1. 2.]


## 5. Simulación de Datos
Instrucción: Genera un array de 1000 números aleatorios que sigan una distribución normal con media 0 y desviación estándar 1. Calcula la media y desviación estándar del array generado.

In [150]:
import numpy as np

datos_simulados = np.random.normal(0, 1, 1000)
media_simulada = np.mean(datos_simulados)
desviacion_simulada = np.std(datos_simulados)

print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)

Media de los datos simulados: 0.008230053285713895
Desviación estándar de los datos simulados: 1.0286458110531616
